import pic from '../assets/images/dp.png'
import pic2 from '../assets/images/lexi.jpg'



export const userData = [
  {
    id: 1,
    firstname: "Reynaldo",
    middleName: "Flores",
    lastname: "Bocaling",
    email: "rey@gmail.com",
    status: 0,
    picture: pic,
    trainer: 'Alex',
    company:'Neust',
    areaofAssignment:'Office',
    cource: 'CICT',
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 1',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 3',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 10,
        timeOut: 6,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },

  {
    id: 2,
    firstname: "Angeline",
    middleName: "Lim",
    lastname: "Untalan",
    email: "rey@gmail.com",
    status: 1,
    picture: pic2,
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 3',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 5',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },
  {
    id: 3,
    firstname: "Kevin",
    middleName: "Mendoza",
    lastname: "Flores",
    email: "rey@gmail.com",
    status: 1,
    picture: pic,
    trainer: 'Alex',
    company:'Neust',
    areaofAssignment:'Office',
    cource: 'CICT',
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 3',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 5',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },
  {
    id: 4,
    firstname: "Mica",
    middleName: "Flores",
    lastname: "Mendoza",
    email: "rey@gmail.com",
    status: 1,
    picture: pic,
    trainer: 'Alex',
    company:'Neust',
    areaofAssignment:'Office',
    cource: 'CRIM',
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 3',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 5',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },
  {
    id: 5,
    firstname: "Anne",
    middleName: "Reyess",
    lastname: "Flores",
    email: "rey@gmail.com",
    status: 1,
    picture: pic,
    trainer: 'Alex',
    company:'Neust',
    areaofAssignment:'Office',
    cource: 'CRIM',
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 3',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 5',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },
  {
    id: 6,
    firstname: "Angelo",
    middleName: "Br",
    lastname: "Brutal",
    email: "rey@gmail.com",
    status: 1,
    picture: pic,
    trainer: 'Alex',
    company:'Neust',
    areaofAssignment:'Office',
    cource: 'EDUC',
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 3',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 5',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },
  {
    id: 7,
    firstname: "Janred",
    middleName: "dssd",
    lastname: "Aquino",
    email: "rey@gmail.com",
    status: 1,
    picture: pic,
    trainer: 'Alex',
    company:'Neust',
    areaofAssignment:'Office',
    cource: 'EDUC',
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 3',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 5',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },
  {
    id: 8,
    firstname: "Glen Mark",
    middleName: "Aquinism",
    lastname: "Mallare",
    email: "rey@gmail.com",
    status: 1,
    picture: pic,
    trainer: 'Alex',
    company:'Neust',
    areaofAssignment:'Office',
    cource: 'NURSE',
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 3',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 5',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },
  {
    id: 9,
    firstname: "Alaine",
    middleName: "Reyes",
    lastname: "Kulbars",
    email: "rey@gmail.com",
    status: 1,
    picture: pic,
    trainer: 'Alex',
    company:'Neust',
    areaofAssignment:'Office',
    cource: 'NURSE',
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 3',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 5',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },
  {
    id: 10,
    firstname: "Neil",
    middleName: "Malabananas",
    lastname: "Velasquez",
    email: "rey@gmail.com",
    status: 1,
    picture: pic,
    trainer: 'Alex',
    company:'Neust',
    areaofAssignment:'Office',
    cource: 'NURSE',
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 3',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 5',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },
  {
    id: 11,
    firstname: "Kian",
    middleName: "dsd",
    lastname: "Garcia",
    email: "rey@gmail.com",
    status: 1,
    picture: pic,
    trainer: 'Alex',
    company:'Neust',
    areaofAssignment:'Office',
    cource: 'CRIM',
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 3',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 5',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },
  {
    id: 12,
    firstname: "Kate",
    middleName: "Delos",
    lastname: "Reyes",
    email: "rey@gmail.com",
    status: 1,
    picture: pic,
    trainer: 'Alex',
    company:'Neust',
    areaofAssignment:'Office',
    cource: 'CRIM',
    timesheet: [
      {
        id: 1,
        tastName: 'create header',
        date: 'january 2',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 2,
        tastName: 'create header',
        date: 'january 3',
        timeIn: 12,
        timeOut: 4,
        totalHours: 7,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 3,
        tastName: 'create sidebar',
        date: 'january 4',
        timeIn: 10,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'january 5',
        timeIn: 10,
        timeOut: 4,
        totalHours: 6,
        attendance_status: 0,
        user_id: 1
      },
      {
        id: 4,
        tastName: 'create sidebar',
        date: 'August 16',
        timeIn: 8,
        timeOut: 4,
        totalHours: 8,
        attendance_status: 1,
        user_id: 1
      },
    ],
  },
]